config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # devise_scope :user do
  #   root to: 'devise/sessions#new'
  # end
  resources :projects do
  	resources :todos
  end
end

app/models/application_record.rb
# Application Record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
# Project model
class Project < ApplicationRecord
  has_many :project_developers
  belongs_to :manager, class_name: 'User', foreign_key: 'manager_id', optional: true
  has_many :developers, through: :project_developers, class_name: 'User', foreign_key: 'user_id'
  
  enum project_type: { web_development: 0, mobile_app: 1, qa: 3}
end

app/models/project_developer.rb
class ProjectDeveloper < ApplicationRecord
  belongs_to :project
  belongs_to :developer, class_name: 'User', foreign_key: 'user_id'
end

app/models/todo.rb
# Todo
class Todo < ApplicationRecord
  belongs_to :project
  belongs_to :developer, class_name: 'User', foreign_key: 'developer_id', optional: true

  enum complexity: { high: 0, medium: 1, low: 2 }
  enum status: { in_progress: 0, complete: 1, block: 2 }
end

app/models/user.rb
# User
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :project_developers
  has_many :projects, through: :project_developers

  enum role: { admin: 0, developer: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  # before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update]
  
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
  	@project = Project.new(project_params.merge(manager_id: current_user.id))
  	respond_to do |format|
  		if @project.save
  			format.html { redirect_to projects_path, notice: 'Project created successflly!' }
  	  else
  	  	format.html { render :new }
  	  end
  	end
  end

  def update
    if @project.update_attributes(project_params)
      format.html { redirect_to projects_path, notice: 'Project Updated successflly!' }
    else
      format.html { render :edit }
    end
  end

  private

  def project_params
  	params.require(:project).permit(:name, :descrition, :project_type, :client_name)
  end

  def set_product
    @project = Project.find(params[:id])
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update]
  before_action :set_project

  def index
    @todos = Todo.all
  end
  
  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params.merge(project_id: @project.id))
    respond_to do |format|
      if @todo.save
        format.html { redirect_to project_todos_path(@project), notice: 'TODO created successflly!' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    if @todo.update_attributes(todot_params)
      format.html { redirect_to todos_path, notice: 'TODO Updated successflly!' }
    else
      format.html { render :edit }
    end
  end

  private

  def todo_params
    params.require(:todo).permit(:name, :complexity, :status, :developer_id, :estimated_time)
  end

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def set_project
    @project = Project.find(params[:project_id])
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:role, :first_name, :last_name])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, 
      :password, :password_confirmation, :role)
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} Brand
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.active
          %a{:href => "#"}
            Link
            %span.sr-only (current)
        %li
          %a{:href => "#"} Link
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Dropdown
            %span.caret
          %ul.dropdown-menu
            %li
              %a{:href => "#"} Action
            %li
              %a{:href => "#"} Another action
            %li
              %a{:href => "#"} Something else here
            %li.divider{:role => "separator"}
            %li
              %a{:href => "#"} Separated link
            %li.divider{:role => "separator"}
            %li
              %a{:href => "#"} One more separated link
      %form.navbar-form.navbar-left
        .form-group
          %input.form-control{:placeholder => "Search", :type => "text"}/
        %button.btn.btn-default{:type => "submit"} Submit
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{:href => "#"} Link
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Dropdown
            %span.caret
          %ul.dropdown-menu
            %li
              = link_to 'Log Out', destroy_user_session_path, method: :delete
            %li
              %a{:href => "#"} Another action
            %li
              %a{:href => "#"} Something else here
            %li.divider{:role => "separator"}
            %li
              %a{:href => "#"} Separated link
    / /.navbar-collapse
  / /.container-fluid

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Pmr
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: 'layouts/header'
    .content
      = yield

app/views/projects/_form.html.haml
= form_for @project do |f|
  .form-group
    = f.label :name
    %br/
    = f.text_field :name, autofocus: true, class: 'form-control'
  .form-group
    = f.label :description
    %br/
    = f.text_field :description, class: 'form-control'
  .form-group
    = f.label :project_type
    %br/
    = f.select :project_type, Project.project_types.keys.map { |t| [t.humanize, t] }, {}, class: 'form-control'
  .form-group
    = f.label :client_name
    %br/
    = f.text_field :client_name, class: 'form-control'
  .actions
    = f.submit @project.persisted? ? 'Update' : 'Cretae', class:'btn btn-default'

app/views/projects/edit.html.haml
%h2.text-center Edit Project
= render partial: 'form'

app/views/projects/index.html.haml
.container
  %h2.text-center Projects
  %table.table
    %thead
      %tr
        %th Project Name
        %th Project Type
        %th Description
        %th Client Name
        %th Action
    %tbody
      - @projects.each do |project|
        %tr
          %td= project.name
          %td= project.project_type
          %td= project.description
          %td= project.client_name
          %td
            = link_to 'Edit', edit_project_path(project)
            = link_to 'Show', project_path(project)
            = link_to 'Add TODO', new_project_todo_path(project)
  
  = link_to 'Add New Project', new_project_path

app/views/projects/new.html.haml
%h2.text-center Create Project
= render partial: 'form'

app/views/todos/_form.html.haml
= form_for @todo, url: project_todos_path(@project) do |f|
  .form-group
    = f.label :name
    %br/
    = f.text_field :name, autofocus: true, class: 'form-control'
  .form-group
    = f.label :complexity
    %br/
    = f.select :complexity, Todo.complexities.keys.map{ |c| [c.humanize, c] }, {}, class: 'form-control'
  .form-group
    = f.label :status
    %br/
    = f.select :status, Todo.statuses.keys.map { |s| [s.humanize, s] }, {}, class: 'form-control'
  .form-group
    = f.label :estimated_time
    %br/
    = f.number_field :estimated_time, class: 'form-control'
  .form-group
    = f.label :developer
    %br/
    = f.select :developer_id, @project.developers.map { |d| [d.name, d.id] }, {}, class: 'form-control'
  .actions
    = f.submit @todo.persisted? ? 'Update' : 'Cretae', class:'btn btn-default'

app/views/todos/edit.html.haml
%h2.text-center Edit Todo
= render partial: 'form'

app/views/todos/index.html.haml
.container
  %h2.text-center Todos
  %table.table
    %thead
      %tr
        %th Name
        %th Complexity
        %th Estimated Time
        %th Status
        %th Owner
        %th Action
    %tbody
      - @todos.each do |todo|
        %tr
          %td= todo.name
          %td= todo.complexity
          %td= todo.estimated_time
          %td= todo.status
          %td= todo.developer.try(:name)
          %td
            = link_to 'Edit', edit_project_todo_path(@project, todo)
            = link_to 'Show', project_todo_path(@project, todo)
  
  = link_to 'Add New TODO', new_project_todo_path(@project)

app/views/todos/new.html.haml
%h2.text-center Create Todo
= render partial: 'form'

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>